//! Snapshot of what `ptsync sync` prints, so console output can't change without
//! someone noticing.

use anyhow::{Context, Result, bail};
use std::fs::File;
use std::path::{Path, PathBuf};
use std::process::Command;

const TAKEOUT_ZIP: &str = "takeout-20240715.zip";
const ARCHIVE_DIR: &str = "photo-archive";

const DEMO_DIR: &str = "target/demo";

const TAPE_CHECK_DIR: &str = "target/demo_tape_check";

const SNAPSHOT_PATH: &str = "tests/snapshots/sync.txt";
const TAPE_PATH: &str = "docs/demo.tape";

const DEMO_NOTE: &str = "photo-archive/2024/05/22/0017-51000.md";

#[test]
fn demo_tape_shows_a_note_ptsync_still_writes() -> Result<()> {
    let root = repo_root()?;
    let demo_dir = prepare_demo_dir(&root, TAPE_CHECK_DIR)?;
    capture(&demo_dir, &sync_argv()?)?;

    assert!(
        demo_dir.join(DEMO_NOTE).is_file(),
        "ptsync no longer writes {DEMO_NOTE}, but {TAPE_PATH} cats it — the GIF \
         would show a missing file. Find where the note moved, then update \
         DEMO_NOTE here and the `cat` line in the tape."
    );

    let tape_path = root.join(TAPE_PATH);
    let tape = std::fs::read_to_string(&tape_path)
        .with_context(|| format!("reading {}", tape_path.display()))?;
    assert!(
        tape.contains(&format!("cat {DEMO_NOTE}")),
        "{TAPE_PATH} no longer cats {DEMO_NOTE}, so the GIF and this test disagree \
         about what the demo shows. Point DEMO_NOTE at whatever the tape now cats."
    );
    Ok(())
}

#[test]
fn sync_output_matches_snapshot() -> Result<()> {
    let root = repo_root()?;
    let demo_dir = prepare_demo_dir(&root, DEMO_DIR)?;
    let output = capture(&demo_dir, &sync_argv()?)?;

    let generated = format!(
        "# Generated by tests/sync_snapshot.rs. Do not edit by hand.\n\
         # `ptsync sync --input {TAKEOUT_ZIP} --output {ARCHIVE_DIR}` against \
         test/takeout_basic.\n\n{output}"
    );

    let snapshot = root.join(SNAPSHOT_PATH);
    if std::env::var_os("UPDATE_DOCS").is_some() {
        if let Some(dir) = snapshot.parent() {
            std::fs::create_dir_all(dir)?;
        }
        std::fs::write(&snapshot, &generated)
            .with_context(|| format!("writing {}", snapshot.display()))?;
        println!("wrote {}", snapshot.display());
        return Ok(());
    }

    let existing = std::fs::read_to_string(&snapshot).unwrap_or_default();
    assert_eq!(
        generated, existing,
        "{SNAPSHOT_PATH} is out of date. Regenerate with:\n\n    \
         UPDATE_DOCS=1 cargo test\n\n\
         Console output changed, so docs/demo.gif is probably stale too:\n\n    \
         vhs docs/demo.tape\n"
    );
    Ok(())
}

/// Cargo runs integration tests with `CARGO_MANIFEST_DIR` set to the package
/// root, the same directory the committed docs live under.
fn repo_root() -> Result<PathBuf> {
    Ok(PathBuf::from(env!("CARGO_MANIFEST_DIR")))
}

/// The `ptsync` binary under test — built by Cargo and handed to us via
/// `CARGO_BIN_EXE_ptsync`, so it always matches the current tree.
fn ptsync_bin() -> PathBuf {
    PathBuf::from(env!("CARGO_BIN_EXE_ptsync"))
}

/// The argv for the sync, run from the directory [`prepare_demo_dir`] creates.
/// `docs/demo.tape` types the same command, so the snapshot really does stand in
/// for what the GIF shows.
fn sync_argv() -> Result<Vec<String>> {
    Ok(vec![
        path_arg(&ptsync_bin())?,
        "sync".to_string(),
        "--input".to_string(),
        TAKEOUT_ZIP.to_string(),
        "--output".to_string(),
        ARCHIVE_DIR.to_string(),
    ])
}

fn prepare_demo_dir(root: &Path, dir: &str) -> Result<PathBuf> {
    let demo_dir = root.join(dir);
    if demo_dir.exists() {
        std::fs::remove_dir_all(&demo_dir)?;
    }
    std::fs::create_dir_all(&demo_dir)?;

    let fixture = root.join("test/takeout_basic");
    if !fixture.is_dir() {
        bail!("missing fixture at {}", fixture.display());
    }
    zip_dir(&fixture, &demo_dir.join(TAKEOUT_ZIP))?;
    Ok(demo_dir)
}

fn capture(cwd: &Path, argv: &[String]) -> Result<String> {
    let (program, args) = argv
        .split_first()
        .context("a step needs at least a program to run")?;
    let output = Command::new(program)
        .args(args)
        .current_dir(cwd)
        .output()
        .with_context(|| format!("running {program}"))?;
    if !output.status.success() {
        bail!(
            "{program} failed with {}:\n{}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    let mut text = String::from_utf8_lossy(&output.stderr).to_string();
    text.push_str(&String::from_utf8_lossy(&output.stdout));
    if text.contains('\u{1b}') {
        bail!(
            "{program} wrote ANSI escapes to a pipe, which would land in {SNAPSHOT_PATH}. \
             Something stopped honouring `IsTerminal` — see `use_colour` in src/main.rs."
        );
    }
    Ok(text)
}

/// Zip `src` into `dest`, mirroring how a downloaded Google Takeout arrives.
fn zip_dir(src: &Path, dest: &Path) -> Result<()> {
    let file = File::create(dest).with_context(|| format!("creating {}", dest.display()))?;
    let mut writer = zip::ZipWriter::new(file);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);

    let mut entries = Vec::new();
    collect_files(src, &mut entries)?;
    // Sorted so the zip's central directory is stable between runs.
    entries.sort();

    for entry in entries {
        let name = relative_to(&entry, src)?;
        writer.start_file(name, options)?;
        let mut input =
            File::open(&entry).with_context(|| format!("opening {}", entry.display()))?;
        std::io::copy(&mut input, &mut writer)?;
    }
    writer.finish()?;
    Ok(())
}

fn collect_files(dir: &Path, found: &mut Vec<PathBuf>) -> Result<()> {
    for entry in std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let path = entry?.path();
        if path.is_dir() {
            collect_files(&path, found)?;
        } else if !is_ignorable(&path) {
            found.push(path);
        }
    }
    Ok(())
}

/// Skip macOS's `.DS_Store` droppings, which would otherwise land in the zip and
/// show up as a skipped file in the demo output.
fn is_ignorable(path: &Path) -> bool {
    path.file_name()
        .map(|name| name == ".DS_Store")
        .unwrap_or(false)
}

fn relative_to(path: &Path, base: &Path) -> Result<String> {
    let rel = path
        .strip_prefix(base)
        .with_context(|| format!("{} should sit under {}", path.display(), base.display()))?;
    Ok(rel.to_string_lossy().replace('\\', "/"))
}

fn path_arg(path: &Path) -> Result<String> {
    Ok(path.to_string_lossy().to_string())
}
