//! Generates `docs/cli.md` from the CLI's own `--help` output. A plain
//! `cargo test` fails if the committed copy is stale; `UPDATE_DOCS=1 cargo test`
//! regenerates it.

use crate::Cli;
use clap::CommandFactory;

const DOC_PATH: &str = "docs/cli.md";
const BIN: &str = crate::COMMAND_NAME;
/// Fixed so the doc renders identically whatever terminal `cargo test` runs in.
const DOC_WIDTH: usize = 100;

/// Drives clap the way the real binary does and captures the resulting help
/// "error", so this is the exact text `<args>` would print.
fn render_help(args: &[&str]) -> anyhow::Result<String> {
    match Cli::command()
        .color(clap::ColorChoice::Never)
        .term_width(DOC_WIDTH)
        .try_get_matches_from(args.iter().copied())
    {
        Ok(_) => anyhow::bail!("--help should produce a DisplayHelp error"),
        Err(err) => Ok(err.render().to_string()),
    }
}

fn generate() -> anyhow::Result<String> {
    let mut out = String::new();
    out.push_str("# CLI reference\n\n");
    out.push_str(&format!(
        "<!-- Generated by the `cli` docs generator from `{BIN} --help`. -->\n"
    ));
    out.push_str("<!-- Do not edit by hand. Run `UPDATE_DOCS=1 cargo test` to regenerate. -->\n\n");

    out.push_str(&format!("## {BIN}\n\n```\n"));
    out.push_str(render_help(&[BIN, "--help"])?.trim_end());
    out.push_str("\n```\n");

    // Read off the command model so new commands document themselves.
    let subcommands: Vec<String> = Cli::command()
        .get_subcommands()
        .map(|s| s.get_name().to_string())
        .filter(|name| name != "help")
        .collect();

    for sub in subcommands {
        out.push_str(&format!("\n## {BIN} {sub}\n\n```\n"));
        out.push_str(render_help(&[BIN, &sub, "--help"])?.trim_end());
        out.push_str("\n```\n");
    }
    Ok(out)
}

#[test]
fn cli_docs_up_to_date() -> anyhow::Result<()> {
    let generated = generate()?;

    if std::env::var_os("UPDATE_DOCS").is_some() {
        if let Some(dir) = std::path::Path::new(DOC_PATH).parent() {
            std::fs::create_dir_all(dir)?;
        }
        std::fs::write(DOC_PATH, &generated)?;
        return Ok(());
    }

    let existing = std::fs::read_to_string(DOC_PATH).unwrap_or_default();
    assert_eq!(
        generated, existing,
        "{DOC_PATH} is out of date. Regenerate with:\n\n    UPDATE_DOCS=1 cargo test\n"
    );
    Ok(())
}
